const QUOTTERY_SC_INDEX = Number(process.env.QUOTTERY_SC_INDEX || 2);
const QUOTTERY_IDENTITY = process.env.QUOTTERY_IDENTITY
  || 'CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACNKL';

const GARTH_ASSET_NAME = 'GARTH';
const GARTH_ISSUER = process.env.GARTH_ISSUER
  || 'PHOENIXCLQOBHDZCHJOCKCPZVTKALQBMXYOEDBUHSDCJRMTUCUBPLSUFNBIE';

const QTRYGOV_ASSET_NAME = 'QTRYGOV';
const QTRYGOV_ISSUER = process.env.QTRYGOV_ISSUER
  || 'CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACNKL';

const GAME_OPERATOR = process.env.QUOTTERY_GAME_OPERATOR
  || 'PREDPWEPWIJUXBLWNCGQSHLRUGVCDANPOHCYHKZYAEVIBEAORRAOWFAHXBJJ';
const EVENT_RESULT_DEPOSIT = String(process.env.QUOTTERY_EVENT_RESULT_DEPOSIT || 1_000_000_000);

const LOG_TYPES = {
  QU_TRANSFER: 0,
  ASSET_OWNERSHIP_CHANGE: 2,
  ASSET_POSSESSION_CHANGE: 3,
  SC_INFO: 6,
};

const SC_LOG_TYPES = {
  CREATED_EVENT: 100001,
  PUBLISH_RESULT: 100002,
  RESOLVE_DISPUTE: 100003,
  FINALIZE_EVENT: 100004,
  UPDATED_NEW_GOV_PARAMS: 100005,
  UPDATED_NEW_DISCOUNT_FEE: 100006,
  UPDATED_NEW_HOSTING_FEE: 100007,
  ARCHIVE_EVENT: 100008,
  MATCH_TYPE_0: 100009,
  MATCH_TYPE_1: 100010,
  MATCH_TYPE_2: 100011,
  MATCH_TYPE_3: 100012,
  ADD_BID: 100013,
  ADD_ASK: 100014,
};

const INPUT_TYPES = {
  CREATE_EVENT: 1,
  ADD_ASK_ORDER: 2,
  REMOVE_ASK_ORDER: 3,
  ADD_BID_ORDER: 4,
  REMOVE_BID_ORDER: 5,
  PUBLISH_RESULT: 6,
  TRY_FINALIZE: 7,
  DISPUTE: 8,
  RESOLVE_DISPUTE: 9,
  USER_CLAIM_REWARD: 10,
  GO_FORCE_CLAIM: 11,
  TRANSFER_QUSD: 12,
  TRANSFER_SHARE_MANAGEMENT: 13,
  CLEAN_MEMORY: 14,
  TRANSFER_QTRYGOV: 15,
  UPDATE_FEE_DISCOUNT_LIST: 20,
  PROPOSAL_VOTE: 100,
};

module.exports = {
  EVENT_RESULT_DEPOSIT,
  GARTH_ASSET_NAME,
  GARTH_ISSUER,
  GAME_OPERATOR,
  INPUT_TYPES,
  LOG_TYPES,
  QTRYGOV_ASSET_NAME,
  QTRYGOV_ISSUER,
  QUOTTERY_IDENTITY,
  QUOTTERY_SC_INDEX,
  SC_LOG_TYPES,
};
